### PR TITLE
[Simplified Chinese] Add missing new strings

### PR DESCRIPTION
**Pull request by lovedebug**
Add new strings except some incorrect strings, which in this case https://github.com/remnoteio/translation/issues/19

### CODE REVIEW

**Comment by dewil-official** [comment]
I manually imported the changes, because this PR again contains changes to the `en` translations that we don't want.

**Comment by lovedebug** [comment]
@dewil-official 

This is strange for me, as i create a new repo to fork. Why is there still met this issue?

**Comment by dewil-official** [comment]
@lovedebug Are you using the Inlang online editor exclusively? It might be an issue on their side then.

Also - did you fully delete your forked repo from your account?

**Comment by lovedebug** [comment]
@dewil-official 

1.  I use inlang online editor to fork and create new repo
2. I have fully deleted the local repo in my space.

**Pull request closed without merging**
